### ISSUE TITLE
Fix ExternalException crash on startup

### ISSUE THREAD

**Issue by krznck** [krznck/CopyFlyouts#66]
Unsure what caused it, and unsure how to replicate it. However, it appears to be a problem with accessing the clipboard, and based on the crash log it should be fixable with a try catch

> 2024-08-14 11:31:17,506 [1] ERROR CopyFlyouts.App - Unhandled UI Exception
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.GetDataObject()
   at System.Windows.Forms.Clipboard.ContainsData(String format, Boolean autoConvert)
   at CopyFlyouts.Core.ClipboardContent.GetDataFromClipboard() in C:\Main\My_Software\CopyFlyouts\Core\ClipboardContent.cs:line 77
   at CopyFlyouts.Core.ClipboardContent.LoadContent() in C:\Main\My_Software\CopyFlyouts\Core\ClipboardContent.cs:line 60
   at CopyFlyouts.Core.CopyCatcher..ctor(SettingsManager userSettings) in C:\Main\My_Software\CopyFlyouts\Core\CopyCatcher.cs:line 44
   at CopyFlyouts.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e) in C:\Main\My_Software\CopyFlyouts\Windows\MainWindow.xaml.cs:line 116
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-08-19 12:28:57,275 [1] ERROR CopyFlyouts.App - Unhandled UI Exception
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.GetDataObject()
   at System.Windows.Forms.Clipboard.ContainsData(String format, Boolean autoConvert)
   at CopyFlyouts.Core.ClipboardContent.GetDataFromClipboard() in C:\Main\My_Software\CopyFlyouts\Core\ClipboardContent.cs:line 78
   at CopyFlyouts.Core.ClipboardContent.LoadContent() in C:\Main\My_Software\CopyFlyouts\Core\ClipboardContent.cs:line 61
   at CopyFlyouts.Core.CopyCatcher..ctor(SettingsManager userSettings) in C:\Main\My_Software\CopyFlyouts\Core\CopyCatcher.cs:line 44
   at CopyFlyouts.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e) in C:\Main\My_Software\CopyFlyouts\Windows\MainWindow.xaml.cs:line 119
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by krznck** [comment]
Had to revert the fix to this bug, as the fix was a workaround that destroyed the actual functionality of the program. This needs to be reconsidered again.

**Comment by krznck** [comment]
It was the `SharpClipboard` package using WinForms instead of WPF, causing unhandled WinForms exceptions to be thrown, when we only catch exceptios with the WPF dispach handler. Should be fixed as of 1.1.2.
